Homework1
made-ml-in-prod-2021/ainureg pull request #2
Opened 2021-05-16 20:19 UTC by ainureg

Использовались предложенные данные.

С помощью консольной программы можно быстро получить модель, прогнать её на тестовых данных. Также приложен jupyter notebook с некоторыми результатами ресерча, показывающие, что это не так уж и плохо.

Весь действующий код расположен в папке src, в папке model хранятся pickle модели лесов. В папке дата настоящие данные, кроме того там же сохраняться сгенерированные данные.

генерация данных, чтение конфигов - src/data

В начале почти  каждого модуля иницируется чтение конфигов, а так же логгер.

По сути рутовой папки быть не должно, старался чтобы все пути были относительными через pathlib. Но рекомендуется запускать все из папки ml_project. Единственная неизвестная мне проблема - логгер, который записывает все в файл. Отключил хандлер все работает из любой папки.

2021-05-23 15:43 UTC, ol-ga-00 requested changes

2021-05-23 15:43 UTC, ol-ga-00 commented on ml_project/src/data/fake_data.py
> +def datagenerate(records: int, headers=columns):
Эта функция нужна только для тестов. Предлагаю перенести её в test/
Также предлагаю из неё сделать фикстуру 
https://habr.com/ru/post/448786/

2021-05-27 17:17 UTC, ainureg commented on ml_project/src/data/fake_data.py
> +def datagenerate(records: int, headers=columns):
правильная фикстура, если я понимаю, должна удалять все после себя, работая только в /tmp

Эти же данные понадобятся во второй части домашки, может и в следующей. Можно, конечно, с собой таскать все данные постоянно, но я как-то сомневаюсь, что это лучше.

я сделал лучше, добавил фикстуру tmpdir, в которой сохраняются фейковые данные, а затем на них на них прогоняется.

![image](https://user-images.githubusercontent.com/5558125/119869110-88d21b00-bf28-11eb-9967-6345ec7bce37.png)

2021-05-30 20:09 UTC, ol-ga-00 commented on ml_project/src/data/fake_data.py
> +def datagenerate(records: int, headers=columns):
Та часть кода, которая не будет использоваться в ПРОМе и которая нужна только для тестов, должна быть вынесена из src/ и помещена в test/

2021-06-02 19:59 UTC, ainureg commented
Хорошо, теперь фейковые данные _только_ в тестах. При желании человек может покопаться в них и сохранить где хочет.

Это потребовало многих изменений путей и многих изменений. В принципе ветка была вся обновлена + к этому обновил read.me для удобства чтения.

2021-06-09 20:37 UTC, ol-ga-00 approved these changes
23 * 0.65 = 14.95
Ставлю 14.95 балла

2021-06-09 20:56 UTC, ainureg commented
Благодарю. Приношу извинения, что затянул, было другое понимание.

Похоже, студент решил проверять и не удалил себя. Я мержу завтра на всякий случай.

2021-06-10 14:07 UTC, merged

2021-06-10 14:07 UTC, ainureg commented
homework 1 сдан