Homework2
made-ml-in-prod-2021/ainureg pull request #3
Opened 2021-05-19 19:38 UTC by ainureg

Сделал что успел, перекинул readme из первой домашки в более логичное место (в её папку)

Доккер работает, модель работает.
Единственное что, фейковые данные, на которые я по умолчанию ссылаюсь - не в гите, надо команду запускать из первого задания, чтобы данные появились.

2021-05-20 08:09 UTC, munraito commented
Привет,
сервис рабочий, запускается без проблем.
Несколько комментариев: не очень удобно, что для генерации запросов нужно также забирать папку с первым ДЗ и разбираться как нагенерить данных оттуда. На мой взгляд, логичнее было бы скопировать этот модуль и во второе ДЗ. Также нет валидации и тестов и докер-образ крупноват.
По самооценке согласен, итого выходит 3+0+2+0+4+0+2+1+1 = **13 баллов**.

2021-05-24 08:07 UTC, Mikhail-M requested changes
кода первой дз не должно быть в этом реквесте

2021-05-24 08:14 UTC, ainureg commented
> кода первой дз не должно быть в этом реквесте

Меня это тоже смутило. Просто дедлайны не так разнятся, первая домашка еще не проверена, и не смержена, а вторая домашка полагается на код первой. Не было очевидно, какое решение правильное.

2021-06-09 08:39 UTC, munraito approved these changes

2021-06-10 14:24 UTC, ainureg commented
> кода первой дз не должно быть в этом реквесте

@Mikhail-M ох ты. Я смержил первую домашку, а при попытке мержа эти сатрые коммиты не пропали. Ожидал, что пропадут, ведь при мерже они совпадают. Честно не очень понимаю как быть. По сути заново создать пул реквест? ав следующий раз просто создавать ветку из main, видимо будет правильно.

2021-06-10 17:26 UTC, Mikhail-M approved these changes
Баллы: 13

2021-06-10 17:37 UTC, merged